-- ==============================================================================
-- SAP HANA CLOUD DATABASE SCHEMA & DASHBOARD DATASETS
-- Schema: "07083DD5224243A8B73B330781FE33B6"
-- Generated for Agro Rate Tracker Enterprise Deployment via hana-mcp-server
-- Database Engine: SAP HANA Cloud In-Memory Column Store
-- ==============================================================================

-- 1. Ensure Schema Initialization
DO BEGIN
  DECLARE schema_exists INT;
  SELECT COUNT(*) INTO schema_exists FROM SYS.SCHEMAS WHERE SCHEMA_NAME = '07083DD5224243A8B73B330781FE33B6';
  IF schema_exists = 0 THEN
    EXEC 'CREATE SCHEMA "07083DD5224243A8B73B330781FE33B6"';
  END IF;
END;

SET SCHEMA "07083DD5224243A8B73B330781FE33B6";

-- ==============================================================================
-- 2. CORE SAP HANA COLUMN STORE TABLES
-- ==============================================================================

-- Table: AGRO_PRICES (Daily Mandi Rates Ingested from Agmarknet)
CREATE COLUMN TABLE "AGRO_PRICES" (
  "ID" NVARCHAR(64) PRIMARY KEY,
  "COMMODITY" NVARCHAR(100) NOT NULL,
  "STATE" NVARCHAR(100) NOT NULL,
  "DISTRICT" NVARCHAR(100) NOT NULL,
  "MARKET" NVARCHAR(100) NOT NULL,
  "VARIETY" NVARCHAR(100),
  "GRADE" NVARCHAR(50),
  "ARRIVAL_DATE" DATE NOT NULL,
  "MIN_PRICE" DECIMAL(12,2) NOT NULL,
  "MAX_PRICE" DECIMAL(12,2) NOT NULL,
  "MODAL_PRICE" DECIMAL(12,2) NOT NULL,
  "SOURCE" NVARCHAR(50) DEFAULT 'agmarknet_api',
  "INGESTED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX "IDX_AGRO_PRICES_LOOKUP" ON "AGRO_PRICES" ("COMMODITY", "STATE", "ARRIVAL_DATE");
CREATE INDEX "IDX_AGRO_PRICES_MARKET" ON "AGRO_PRICES" ("MARKET", "DISTRICT");

-- Table: USER_PROFILES (Multi-Role Authentication Directory: Farmer, Customer, Trader, Admin)
CREATE COLUMN TABLE "USER_PROFILES" (
  "ID" NVARCHAR(64) PRIMARY KEY,
  "USER_ID" NVARCHAR(64) NOT NULL,
  "NAME" NVARCHAR(150) NOT NULL,
  "EMAIL" NVARCHAR(150) UNIQUE,
  "PHONE" NVARCHAR(50),
  "ROLE" NVARCHAR(30) NOT NULL, -- 'farmer', 'customer', 'trader', 'admin'
  "STATE" NVARCHAR(100) NOT NULL,
  "DISTRICT" NVARCHAR(100) NOT NULL,
  "LATITUDE" DOUBLE,
  "LONGITUDE" DOUBLE,
  "LANGUAGE" NVARCHAR(10) DEFAULT 'en', -- 'en', 'ta', 'hi'
  "EDGE_STORAGE_ENABLED" BOOLEAN DEFAULT FALSE,
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: FARMER_LISTINGS (Farmer Hub Harvest Inventory for Direct Trade)
CREATE COLUMN TABLE "FARMER_LISTINGS" (
  "ID" NVARCHAR(64) PRIMARY KEY,
  "FARMER_ID" NVARCHAR(64) NOT NULL,
  "FARMER_NAME" NVARCHAR(150) NOT NULL,
  "CROP" NVARCHAR(100) NOT NULL,
  "VARIETY" NVARCHAR(100),
  "GRADE" NVARCHAR(50) DEFAULT 'FAQ',
  "QUANTITY_AVAILABLE" DECIMAL(12,2) NOT NULL,
  "INITIAL_QUANTITY" DECIMAL(12,2),
  "UNIT" NVARCHAR(20) DEFAULT 'quintal', -- 'quintal', 'kg', 'tonne'
  "ASKING_PRICE_PER_UNIT" DECIMAL(12,2) NOT NULL,
  "STATE" NVARCHAR(100) NOT NULL,
  "DISTRICT" NVARCHAR(100) NOT NULL,
  "LATITUDE" DOUBLE,
  "LONGITUDE" DOUBLE,
  "AVAILABLE_FROM" DATE,
  "AVAILABLE_UNTIL" DATE,
  "STATUS" NVARCHAR(20) DEFAULT 'active', -- 'active', 'paused', 'sold'
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: CUSTOMER_REQUIREMENTS (Buyer Purchase Demands)
CREATE COLUMN TABLE "CUSTOMER_REQUIREMENTS" (
  "ID" NVARCHAR(64) PRIMARY KEY,
  "CUSTOMER_ID" NVARCHAR(64) NOT NULL,
  "CUSTOMER_NAME" NVARCHAR(150) NOT NULL,
  "CROP" NVARCHAR(100) NOT NULL,
  "QUANTITY" DECIMAL(12,2) NOT NULL,
  "UNIT" NVARCHAR(20) DEFAULT 'quintal',
  "MAX_BUDGET_PER_UNIT" DECIMAL(12,2) NOT NULL,
  "DELIVERY_STATE" NVARCHAR(100) NOT NULL,
  "DELIVERY_DISTRICT" NVARCHAR(100) NOT NULL,
  "LATITUDE" DOUBLE,
  "LONGITUDE" DOUBLE,
  "REQUIRED_BY_DATE" DATE NOT NULL,
  "STATUS" NVARCHAR(20) DEFAULT 'open', -- 'open', 'matched', 'fulfilled'
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: DEAL_PROPOSALS (Algorithmic Match Engine Results)
CREATE COLUMN TABLE "DEAL_PROPOSALS" (
  "ID" NVARCHAR(64) PRIMARY KEY,
  "REQUIREMENT_ID" NVARCHAR(64) NOT NULL,
  "LISTING_ID" NVARCHAR(64) NOT NULL,
  "FARMER_ID" NVARCHAR(64) NOT NULL,
  "FARMER_NAME" NVARCHAR(150) NOT NULL,
  "CUSTOMER_ID" NVARCHAR(64) NOT NULL,
  "CUSTOMER_NAME" NVARCHAR(150) NOT NULL,
  "CROP" NVARCHAR(100) NOT NULL,
  "QUANTITY" DECIMAL(12,2) NOT NULL,
  "UNIT" NVARCHAR(20) DEFAULT 'quintal',
  "PRICE_PER_UNIT" DECIMAL(12,2) NOT NULL,
  "DISTANCE_KM" DECIMAL(10,2) NOT NULL,
  "DELIVERY_COST_ESTIMATE" DECIMAL(12,2) NOT NULL,
  "TOTAL_COST" DECIMAL(14,2) NOT NULL,
  "MATCH_SCORE" DECIMAL(5,2) NOT NULL,
  "IS_ALTERNATIVE" BOOLEAN DEFAULT FALSE,
  "STATUS" NVARCHAR(20) DEFAULT 'pending', -- 'pending', 'accepted', 'rejected', 'expired'
  "EXPIRES_AT" TIMESTAMP NOT NULL,
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: ORDERS (Executed Contracts Between Farmers and Buyers)
CREATE COLUMN TABLE "ORDERS" (
  "ID" NVARCHAR(64) PRIMARY KEY,
  "DEAL_ID" NVARCHAR(64) NOT NULL,
  "CUSTOMER_ID" NVARCHAR(64) NOT NULL,
  "CUSTOMER_NAME" NVARCHAR(150) NOT NULL,
  "FARMER_ID" NVARCHAR(64) NOT NULL,
  "FARMER_NAME" NVARCHAR(150) NOT NULL,
  "CROP" NVARCHAR(100) NOT NULL,
  "VARIETY" NVARCHAR(100),
  "GRADE" NVARCHAR(50),
  "QUANTITY" DECIMAL(12,2) NOT NULL,
  "UNIT" NVARCHAR(20) DEFAULT 'quintal',
  "PRICE_PER_UNIT" DECIMAL(12,2) NOT NULL,
  "DELIVERY_COST" DECIMAL(12,2) NOT NULL,
  "TOTAL_AMOUNT" DECIMAL(14,2) NOT NULL,
  "STATUS" NVARCHAR(30) DEFAULT 'confirmed', -- 'confirmed', 'packed', 'dispatched', 'in_transit', 'delivered', 'completed'
  "EXPECTED_DELIVERY_DATE" DATE NOT NULL,
  "IS_DEMO" BOOLEAN DEFAULT FALSE,
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: ORDER_EVENTS (Tracking Milestone Audit Trail)
CREATE COLUMN TABLE "ORDER_EVENTS" (
  "ID" NVARCHAR(64) PRIMARY KEY,
  "ORDER_ID" NVARCHAR(64) NOT NULL,
  "STATUS" NVARCHAR(30) NOT NULL,
  "NOTE" NVARCHAR(500),
  "ACTOR_ROLE" NVARCHAR(30) NOT NULL,
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: PRICE_FORECASTS (7-Day Predictive Horizon from Time-Series Models)
CREATE COLUMN TABLE "PRICE_FORECASTS" (
  "ID" NVARCHAR(64) PRIMARY KEY,
  "CROP" NVARCHAR(100) NOT NULL,
  "MARKET" NVARCHAR(100),
  "STATE" NVARCHAR(100),
  "TARGET_DATE" DATE NOT NULL,
  "PREDICTED_MODAL" DECIMAL(12,2) NOT NULL,
  "CONFIDENCE_LOWER" DECIMAL(12,2) NOT NULL,
  "CONFIDENCE_UPPER" DECIMAL(12,2) NOT NULL,
  "TREND_DIRECTION" NVARCHAR(20), -- 'up', 'down', 'stable'
  "MAPE_BACKTEST_PCT" DECIMAL(5,2),
  "MODEL_NAME" NVARCHAR(50) DEFAULT 'ExponentialSmoothing-HoltWinters',
  "GENERATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: PRICE_ANOMALIES (IQR Statistical Volatility & Price Spikes)
CREATE COLUMN TABLE "PRICE_ANOMALIES" (
  "ID" NVARCHAR(64) PRIMARY KEY,
  "CROP" NVARCHAR(100) NOT NULL,
  "MARKET" NVARCHAR(100) NOT NULL,
  "STATE" NVARCHAR(100) NOT NULL,
  "RECORDED_MODAL" DECIMAL(12,2) NOT NULL,
  "BENCHMARK_MODAL" DECIMAL(12,2) NOT NULL,
  "DEVIATION_PCT" DECIMAL(6,2) NOT NULL,
  "DIRECTION" NVARCHAR(10) NOT NULL, -- 'Above', 'Below'
  "SEVERITY" NVARCHAR(10) NOT NULL,  -- 'High', 'Moderate'
  "Z_SCORE" DECIMAL(6,2),
  "DETECTED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: PRICE_ALERTS (User Notification Subscriptions)
CREATE COLUMN TABLE "PRICE_ALERTS" (
  "ID" NVARCHAR(64) PRIMARY KEY,
  "USER_ID" NVARCHAR(64) NOT NULL,
  "CROP" NVARCHAR(100) NOT NULL,
  "STATE" NVARCHAR(100),
  "TARGET_PRICE" DECIMAL(12,2) NOT NULL,
  "CONDITION" NVARCHAR(20) NOT NULL, -- 'above', 'below'
  "ACTIVE" BOOLEAN DEFAULT TRUE,
  "LAST_TRIGGERED_AT" TIMESTAMP,
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: USER_NOTIFICATIONS (Delivered Alerts and Operational Updates)
CREATE COLUMN TABLE "USER_NOTIFICATIONS" (
  "ID" NVARCHAR(64) PRIMARY KEY,
  "USER_ID" NVARCHAR(64) NOT NULL,
  "TYPE" NVARCHAR(30) NOT NULL, -- 'deal', 'order', 'price_alert', 'system'
  "TITLE" NVARCHAR(200) NOT NULL,
  "MESSAGE" NVARCHAR(1000) NOT NULL,
  "READ" BOOLEAN DEFAULT FALSE,
  "LINK" NVARCHAR(250),
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table: INGESTION_LOGS (Data Feed Sync Audit Log)
CREATE COLUMN TABLE "INGESTION_LOGS" (
  "ID" NVARCHAR(64) PRIMARY KEY,
  "RUN_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "SOURCE" NVARCHAR(50) NOT NULL,
  "FETCHED" INTEGER NOT NULL,
  "ACCEPTED" INTEGER NOT NULL,
  "REJECTED" INTEGER NOT NULL,
  "MESSAGE" NVARCHAR(500)
);

-- Table: APP_SETTINGS (System Tuning & Scoring Parameters)
CREATE COLUMN TABLE "APP_SETTINGS" (
  "KEY" NVARCHAR(50) PRIMARY KEY,
  "VALUE_NUM" DECIMAL(12,2),
  "VALUE_STR" NVARCHAR(250),
  "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- 3. ANALYTICAL DATASETS (SAP HANA COLUMN VIEWS BY DASHBOARD)
-- ==============================================================================

-- DATASET 1: Executive Dashboard Pulse Dataset
-- Dashboard: Main Home / Executive Dashboard
CREATE OR REPLACE VIEW "V_DASHBOARD_COMMODITY_METRICS" AS
SELECT 
  "COMMODITY",
  COUNT(DISTINCT "MARKET") AS "ACTIVE_MANDIS_COUNT",
  COUNT(DISTINCT "STATE") AS "STATES_REPORTING",
  ROUND(AVG("MODAL_PRICE"), 2) AS "AVG_MODAL_PRICE_QTL",
  ROUND(AVG("MODAL_PRICE") / 100.0, 2) AS "AVG_MODAL_PRICE_KG",
  MIN("MIN_PRICE") AS "LOWEST_MANDI_PRICE",
  MAX("MAX_PRICE") AS "HIGHEST_MANDI_PRICE",
  ROUND(MAX("MAX_PRICE") - MIN("MIN_PRICE"), 2) AS "NATIONAL_SPREAD",
  MAX("ARRIVAL_DATE") AS "LATEST_DATA_DATE"
FROM "AGRO_PRICES"
GROUP BY "COMMODITY";

-- DATASET 2: Market Prices Explorer Dataset
-- Dashboard: Market Prices Page (/prices)
CREATE OR REPLACE VIEW "V_MARKET_PRICES_EXPLORER" AS
SELECT
  p."ID",
  p."COMMODITY",
  p."STATE",
  p."DISTRICT",
  p."MARKET",
  p."VARIETY",
  p."GRADE",
  p."ARRIVAL_DATE",
  p."MIN_PRICE" AS "MIN_PRICE_QTL",
  p."MAX_PRICE" AS "MAX_PRICE_QTL",
  p."MODAL_PRICE" AS "MODAL_PRICE_QTL",
  ROUND(p."MODAL_PRICE" / 100.0, 2) AS "MODAL_PRICE_KG",
  ROUND(p."MAX_PRICE" - p."MIN_PRICE", 2) AS "DAILY_MANDI_SPREAD",
  p."SOURCE"
FROM "AGRO_PRICES" p;

-- DATASET 3: Price Comparison & Arbitrage Spread Dataset
-- Dashboard: Compare Page (/compare)
CREATE OR REPLACE VIEW "V_COMPARE_INTER_MANDI_SPREAD" AS
SELECT
  a."COMMODITY",
  a."MARKET" AS "ORIGIN_MARKET",
  a."STATE" AS "ORIGIN_STATE",
  a."MODAL_PRICE" AS "ORIGIN_PRICE_QTL",
  b."MARKET" AS "DESTINATION_MARKET",
  b."STATE" AS "DESTINATION_STATE",
  b."MODAL_PRICE" AS "DESTINATION_PRICE_QTL",
  ROUND(b."MODAL_PRICE" - a."MODAL_PRICE", 2) AS "ARBITRAGE_SPREAD_QTL",
  ROUND(((b."MODAL_PRICE" - a."MODAL_PRICE") / a."MODAL_PRICE") * 100.0, 2) AS "SPREAD_PERCENTAGE",
  a."ARRIVAL_DATE"
FROM "AGRO_PRICES" a
JOIN "AGRO_PRICES" b 
  ON a."COMMODITY" = b."COMMODITY" 
 AND a."ARRIVAL_DATE" = b."ARRIVAL_DATE"
 AND a."ID" != b."ID"
WHERE b."MODAL_PRICE" > a."MODAL_PRICE";

-- DATASET 4: Historical Trends & Momentum Dataset
-- Dashboard: Trends Page (/trends)
CREATE OR REPLACE VIEW "V_TRENDS_7D_MOVING_AVG" AS
SELECT
  "COMMODITY",
  "STATE",
  "ARRIVAL_DATE",
  ROUND(AVG("MODAL_PRICE"), 2) AS "DAILY_AVG_MODAL",
  ROUND(AVG(AVG("MODAL_PRICE")) OVER (
    PARTITION BY "COMMODITY", "STATE" 
    ORDER BY "ARRIVAL_DATE" 
    ROWS BETWEEN 6 PRECEDING AND CURRENT ROW
  ), 2) AS "ROLLING_7D_MA"
FROM "AGRO_PRICES"
GROUP BY "COMMODITY", "STATE", "ARRIVAL_DATE";

-- DATASET 5: Top Movers & Volatility Ranking Dataset
-- Dashboard: Top Movers Page (/movers)
CREATE OR REPLACE VIEW "V_TOP_MOVERS_MOMENTUM" AS
SELECT
  p."COMMODITY",
  p."MARKET",
  p."STATE",
  p."MODAL_PRICE" AS "CURRENT_PRICE",
  ROUND(p."MODAL_PRICE" - (SELECT AVG("MODAL_PRICE") FROM "AGRO_PRICES" sub WHERE sub."COMMODITY" = p."COMMODITY"), 2) AS "DELTA_VS_AVG",
  ROUND(((p."MODAL_PRICE" - (SELECT AVG("MODAL_PRICE") FROM "AGRO_PRICES" sub WHERE sub."COMMODITY" = p."COMMODITY")) / 
    (SELECT AVG("MODAL_PRICE") FROM "AGRO_PRICES" sub WHERE sub."COMMODITY" = p."COMMODITY")) * 100.0, 2) AS "MOMENTUM_PCT",
  CASE 
    WHEN p."MODAL_PRICE" > (SELECT AVG("MODAL_PRICE") * 1.15 FROM "AGRO_PRICES" sub WHERE sub."COMMODITY" = p."COMMODITY") THEN 'High Gainer'
    WHEN p."MODAL_PRICE" < (SELECT AVG("MODAL_PRICE") * 0.85 FROM "AGRO_PRICES" sub WHERE sub."COMMODITY" = p."COMMODITY") THEN 'Heavy Drop'
    ELSE 'Steady Corridor'
  END AS "VELOCITY_TIER"
FROM "AGRO_PRICES" p;

-- DATASET 6: 7-Day Forward Price Projections Dataset
-- Dashboard: Forecast Page (/forecast)
CREATE OR REPLACE VIEW "V_FORECAST_7DAY_PROJECTIONS" AS
SELECT
  "ID",
  "CROP",
  "MARKET",
  "STATE",
  "TARGET_DATE",
  "PREDICTED_MODAL",
  ROUND("PREDICTED_MODAL" / 100.0, 2) AS "PREDICTED_MODAL_KG",
  "CONFIDENCE_LOWER",
  "CONFIDENCE_UPPER",
  ROUND("CONFIDENCE_UPPER" - "CONFIDENCE_LOWER", 2) AS "UNCERTAINTY_BAND",
  "TREND_DIRECTION",
  "MAPE_BACKTEST_PCT"
FROM "PRICE_FORECASTS";

-- DATASET 7: Price Anomalies & Volatility Shocks Dataset
-- Dashboard: Anomalies Page (/anomalies)
CREATE OR REPLACE VIEW "V_ANOMALIES_SEVERITY_FEED" AS
SELECT
  a."ID",
  a."CROP",
  a."MARKET",
  a."STATE",
  a."RECORDED_MODAL",
  a."BENCHMARK_MODAL",
  a."DEVIATION_PCT",
  a."DIRECTION",
  a."SEVERITY",
  a."Z_SCORE",
  a."DETECTED_AT",
  CASE 
    WHEN a."DIRECTION" = 'Above' AND a."SEVERITY" = 'High' THEN 'Urgent Buyer Alert: Supply Constraint'
    WHEN a."DIRECTION" = 'Below' AND a."SEVERITY" = 'High' THEN 'Urgent Farmer Alert: Distress Pricing'
    ELSE 'Noticeable Spread Variation'
  END AS "ANOMALY_IMPACT_NOTE"
FROM "PRICE_ANOMALIES" a;

-- DATASET 8: Farmer Hub Harvest Inventory & Benchmarks Dataset
-- Dashboard: Farmer Hub Page (/farmer-hub)
CREATE OR REPLACE VIEW "V_FARMER_HUB_INVENTORY" AS
SELECT
  l."ID" AS "LISTING_ID",
  l."FARMER_ID",
  l."FARMER_NAME",
  l."CROP",
  l."VARIETY",
  l."GRADE",
  l."QUANTITY_AVAILABLE",
  l."UNIT",
  l."ASKING_PRICE_PER_UNIT",
  l."STATE",
  l."DISTRICT",
  l."STATUS",
  ROUND((SELECT AVG("MODAL_PRICE") FROM "AGRO_PRICES" p WHERE p."COMMODITY" = l."CROP" AND p."STATE" = l."STATE"), 2) AS "LOCAL_MANDI_BENCHMARK",
  ROUND(l."ASKING_PRICE_PER_UNIT" - 
    (SELECT AVG("MODAL_PRICE") FROM "AGRO_PRICES" p WHERE p."COMMODITY" = l."CROP" AND p."STATE" = l."STATE"), 2) AS "PREMIUM_VS_MANDI",
  l."CREATED_AT"
FROM "FARMER_LISTINGS" l;

-- DATASET 9: Buyer Produce Marketplace & Deals Dataset
-- Dashboard: Find Produce Page (/find-produce)
CREATE OR REPLACE VIEW "V_FIND_PRODUCE_MARKETPLACE" AS
SELECT
  r."ID" AS "REQUIREMENT_ID",
  r."CUSTOMER_NAME",
  r."CROP",
  r."QUANTITY" AS "REQUESTED_QUANTITY",
  r."MAX_BUDGET_PER_UNIT",
  r."DELIVERY_DISTRICT",
  r."DELIVERY_STATE",
  r."REQUIRED_BY_DATE",
  COUNT(p."ID") AS "CANDIDATE_MATCHES_COUNT",
  MAX(p."MATCH_SCORE") AS "HIGHEST_MATCH_SCORE"
FROM "CUSTOMER_REQUIREMENTS" r
LEFT JOIN "DEAL_PROPOSALS" p ON r."ID" = p."REQUIREMENT_ID"
GROUP BY 
  r."ID", r."CUSTOMER_NAME", r."CROP", r."QUANTITY", 
  r."MAX_BUDGET_PER_UNIT", r."DELIVERY_DISTRICT", r."DELIVERY_STATE", r."REQUIRED_BY_DATE";

-- DATASET 10: Produce Orders & Logistics Fulfillment Pipeline
-- Dashboard: Orders Page (/orders)
CREATE OR REPLACE VIEW "V_ORDERS_FULFILLMENT_PIPELINE" AS
SELECT
  o."ID" AS "ORDER_ID",
  o."CUSTOMER_NAME",
  o."FARMER_NAME",
  o."CROP",
  o."QUANTITY",
  o."UNIT",
  o."PRICE_PER_UNIT",
  o."DELIVERY_COST",
  o."TOTAL_AMOUNT",
  o."STATUS" AS "CURRENT_STAGE",
  o."EXPECTED_DELIVERY_DATE",
  (SELECT COUNT(*) FROM "ORDER_EVENTS" e WHERE e."ORDER_ID" = o."ID") AS "MILESTONES_LOGGED",
  o."CREATED_AT"
FROM "ORDERS" o;

-- DATASET 11: Commodity Supply & Demand Equilibrium Dataset
-- Dashboard: Supply & Demand Page (/supply-demand)
CREATE OR REPLACE VIEW "V_SUPPLY_DEMAND_EQUILIBRIUM" AS
SELECT
  COALESCE(s."CROP", d."CROP") AS "COMMODITY",
  COALESCE(s."TOTAL_SUPPLY_QTL", 0) AS "FARMER_SUPPLY_QTL",
  COALESCE(d."TOTAL_DEMAND_QTL", 0) AS "BUYER_DEMAND_QTL",
  ROUND(COALESCE(s."TOTAL_SUPPLY_QTL", 0) - COALESCE(d."TOTAL_DEMAND_QTL", 0), 2) AS "NET_BALANCE_QTL",
  CASE
    WHEN COALESCE(d."TOTAL_DEMAND_QTL", 0) = 0 THEN 999.0
    ELSE ROUND(COALESCE(s."TOTAL_SUPPLY_QTL", 0) / COALESCE(d."TOTAL_DEMAND_QTL", 0), 2)
  END AS "SUPPLY_DEMAND_RATIO",
  CASE
    WHEN COALESCE(s."TOTAL_SUPPLY_QTL", 0) > COALESCE(d."TOTAL_DEMAND_QTL", 0) * 1.2 THEN 'Market Surplus (Softening Rate)'
    WHEN COALESCE(d."TOTAL_DEMAND_QTL", 0) > COALESCE(s."TOTAL_SUPPLY_QTL", 0) * 1.2 THEN 'High Demand Deficit (Hardening Rate)'
    ELSE 'Balanced Equilibrium'
  END AS "MARKET_EQUILIBRIUM_STATE"
FROM (
  SELECT "CROP", SUM("QUANTITY_AVAILABLE") AS "TOTAL_SUPPLY_QTL"
  FROM "FARMER_LISTINGS"
  WHERE "STATUS" = 'active'
  GROUP BY "CROP"
) s
FULL OUTER JOIN (
  SELECT "CROP", SUM("QUANTITY") AS "TOTAL_DEMAND_QTL"
  FROM "CUSTOMER_REQUIREMENTS"
  WHERE "STATUS" = 'open'
  GROUP BY "CROP"
) d ON s."CROP" = d."CROP";

-- DATASET 12: Price Alerts Active Monitor Dataset
-- Dashboard: Alerts Page (/alerts)
CREATE OR REPLACE VIEW "V_PRICE_ALERTS_MONITOR" AS
SELECT
  a."ID" AS "ALERT_ID",
  a."USER_ID",
  u."NAME" AS "USER_NAME",
  u."ROLE" AS "USER_ROLE",
  a."CROP",
  a."STATE",
  a."TARGET_PRICE",
  a."CONDITION",
  ROUND((SELECT AVG("MODAL_PRICE") FROM "AGRO_PRICES" p WHERE p."COMMODITY" = a."CROP"), 2) AS "CURRENT_MODAL_PRICE",
  CASE
    WHEN a."CONDITION" = 'above' AND (SELECT AVG("MODAL_PRICE") FROM "AGRO_PRICES" p WHERE p."COMMODITY" = a."CROP") >= a."TARGET_PRICE" THEN 'TRIGGER_READY'
    WHEN a."CONDITION" = 'below' AND (SELECT AVG("MODAL_PRICE") FROM "AGRO_PRICES" p WHERE p."COMMODITY" = a."CROP") <= a."TARGET_PRICE" THEN 'TRIGGER_READY'
    ELSE 'MONITORING'
  END AS "TRIGGER_STATUS"
FROM "PRICE_ALERTS" a
JOIN "USER_PROFILES" u ON a."USER_ID" = u."ID"
WHERE a."ACTIVE" = TRUE;

-- DATASET 13: Admin System Governance & Platform Metrics Dataset
-- Dashboard: Admin Console (/admin)
CREATE OR REPLACE VIEW "V_ADMIN_SYSTEM_METRICS" AS
SELECT
  (SELECT COUNT(*) FROM "USER_PROFILES") AS "TOTAL_USERS",
  (SELECT COUNT(*) FROM "USER_PROFILES" WHERE "ROLE" = 'farmer') AS "FARMER_USERS",
  (SELECT COUNT(*) FROM "USER_PROFILES" WHERE "ROLE" = 'customer') AS "BUYER_USERS",
  (SELECT COUNT(*) FROM "USER_PROFILES" WHERE "ROLE" = 'trader') AS "TRADER_USERS",
  (SELECT COUNT(*) FROM "USER_PROFILES" WHERE "EDGE_STORAGE_ENABLED" = TRUE) AS "EDGE_PERSISTENT_FARMERS",
  (SELECT COUNT(*) FROM "AGRO_PRICES") AS "TOTAL_MANDI_PRICE_RECORDS",
  (SELECT COUNT(*) FROM "FARMER_LISTINGS" WHERE "STATUS" = 'active') AS "ACTIVE_FARMER_LISTINGS",
  (SELECT COUNT(*) FROM "CUSTOMER_REQUIREMENTS" WHERE "STATUS" = 'open') AS "OPEN_BUYER_REQUIREMENTS",
  (SELECT COUNT(*) FROM "ORDERS") AS "TOTAL_ORDERS_PLACED",
  (SELECT COALESCE(SUM("TOTAL_AMOUNT"), 0) FROM "ORDERS") AS "TOTAL_TRANSACTION_VALUE_INR",
  (SELECT MAX("RUN_AT") FROM "INGESTION_LOGS") AS "LAST_DATA_SYNC_TIMESTAMP"
FROM DUMMY;

-- ==============================================================================
-- 4. SEED DATASETS FOR IMMEDIATE SAP HANA QUERY EXECUTION
-- ==============================================================================

-- Seed User Profiles
UPSERT "USER_PROFILES" VALUES ('user-admin-1', 'user-admin-1', 'Mandi Admin (Govt Directorate)', 'admin@agrorate.gov.in', '+91-11-2338-0001', 'admin', 'NCT of Delhi', 'Delhi', 28.7041, 77.1025, 'en', FALSE, CURRENT_TIMESTAMP) WITH PRIMARY KEY;
UPSERT "USER_PROFILES" VALUES ('farmer-1', 'farmer-1', 'Ramesh Kumar (Krishnagiri Farm)', 'farmer.ramesh@agrorate.in', '+91-94431-12345', 'farmer', 'Tamil Nadu', 'Krishnagiri', 12.5266, 78.2146, 'ta', TRUE, CURRENT_TIMESTAMP) WITH PRIMARY KEY;
UPSERT "USER_PROFILES" VALUES ('user-customer-1', 'user-customer-1', 'Priya Sharma (GreenGrocer Co.)', 'customer.priya@agrorate.in', '+91-98401-23456', 'customer', 'Tamil Nadu', 'Chennai', 13.0827, 80.2707, 'en', FALSE, CURRENT_TIMESTAMP) WITH PRIMARY KEY;
UPSERT "USER_PROFILES" VALUES ('user-trader-1', 'user-trader-1', 'Anand Agrico Mandi Traders', 'trader.anand@agrorate.in', '+91-98200-98765', 'trader', 'Maharashtra', 'Mumbai', 19.0760, 72.8777, 'en', FALSE, CURRENT_TIMESTAMP) WITH PRIMARY KEY;

-- Seed Settings
UPSERT "APP_SETTINGS" VALUES ('weight_price', 30.0, 'Price competitiveness weight', CURRENT_TIMESTAMP) WITH PRIMARY KEY;
UPSERT "APP_SETTINGS" VALUES ('weight_distance', 25.0, 'Haulage distance weight', CURRENT_TIMESTAMP) WITH PRIMARY KEY;
UPSERT "APP_SETTINGS" VALUES ('delivery_base_fee', 300.0, 'Base delivery fee INR', CURRENT_TIMESTAMP) WITH PRIMARY KEY;
UPSERT "APP_SETTINGS" VALUES ('delivery_per_km_tonne', 3.5, 'Haulage rate per km tonne', CURRENT_TIMESTAMP) WITH PRIMARY KEY;

-- ==============================================================================
-- END OF SAP HANA CLOUD SCHEMA
-- ==============================================================================
